server:
  host: localhost
  port: 8080
database:
  host: localhost
  username: postgres
  password: 1
  dbname: adfy_com
  port: 5432
  timezone: Europe/Kiev
jwt:
  secret: test
  duration: 43200 
  algo: HS256