// Code generated by dingo; DO NOT EDIT
package main

import kernel "adfy.com/internal/kernel"

type Container struct {
	Db	*kernel.Db
	Orm	*kernel.Orm
}

var DefaultContainer = NewContainer()

func NewContainer() *Container {
	return &Container{}
}
func (container *Container) GetDb() *kernel.Db {
	if container.Db == nil {
		service := db.NewDb()
		container.Db = service
	}
	return container.Db
}
func (container *Container) GetOrm() *kernel.Orm {
	if container.Orm == nil {
		service := db.NewGorm(container.GetDb())
		container.Orm = service
	}
	return container.Orm
}
