consumes:
- application/json
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
info:
  title: project/service.proto
  version: version not set
paths:
  /twirp/adfy.io.rpc.project.ProjectService/CreateProject:
    post:
      tags:
      - ProjectService
      operationId: CreateProject
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/projectProjectRequest'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/projectProjectResponse'
  /twirp/adfy.io.rpc.project.ProjectService/EditProject:
    post:
      tags:
      - ProjectService
      operationId: EditProject
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/projectProjectRequest'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/projectProjectResponse'
  /twirp/adfy.io.rpc.user.UserService/Me:
    post:
      tags:
      - UserService
      operationId: Me
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/userEmpty'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/userMeResponse'
  /twirp/adfy.io.rpc.user.UserService/SignIn:
    post:
      tags:
      - UserService
      operationId: SignIn
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/userSignInRequest'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/userSignInResponse'
  /twirp/adfy.io.rpc.user.UserService/SignUp:
    post:
      tags:
      - UserService
      operationId: SignUp
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/userSignUpRequest'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/userSignUpResponse'
definitions:
  projectProjectRequest:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      website:
        type: string
  projectProjectResponse:
    type: object
    properties:
      id:
        type: string
      result:
        type: boolean
        format: boolean
  userEmpty:
    type: object
  userMeResponse:
    type: object
    properties:
      email:
        type: string
      name:
        type: string
  userSignInRequest:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
      rememberMe:
        type: boolean
        format: boolean
  userSignInResponse:
    type: object
    properties:
      token:
        type: string
  userSignUpRequest:
    type: object
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
  userSignUpResponse:
    type: object
    properties:
      token:
        type: string
externalDocs:
  description: Adfy.io github repository
  url: https://github.com/vldmr-k/adfy.io
