consumes:
- application/json
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
info:
  title: service.proto
  version: version not set
host: localhost
paths:
  /twirp/adfy.io.rpc.project.ProjectService/CreateProject:
    post:
      tags:
      - ProjectService
      operationId: CreateProject
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/adfy.io.rpc.project_ProjectRequest'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/adfy.io.rpc.project_ProjectResponse'
  /twirp/adfy.io.rpc.project.ProjectService/EditProject:
    post:
      tags:
      - ProjectService
      operationId: EditProject
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/adfy.io.rpc.project_ProjectRequest'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/adfy.io.rpc.project_ProjectResponse'
  /twirp/adfy.io.rpc.user.UserService/Register:
    post:
      tags:
      - UserService
      operationId: Register
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/adfy.io.rpc.user_RegisterRequest'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/adfy.io.rpc.user_RegisterResponse'
  /twirp/adfy.io.rpc.user.UserService/SignIn:
    post:
      tags:
      - UserService
      operationId: SignIn
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/adfy.io.rpc.user_SignInRequest'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/adfy.io.rpc.user_SignInResponse'
definitions:
  adfy.io.rpc.project_ProjectRequest:
    description: 'Fields: id, name, website'
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      website:
        type: string
  adfy.io.rpc.project_ProjectResponse:
    description: 'Fields: id, result'
    type: object
    properties:
      id:
        type: string
      result:
        type: boolean
  adfy.io.rpc.user_RegisterRequest:
    description: 'Fields: name, email, password'
    type: object
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
  adfy.io.rpc.user_RegisterResponse:
    description: 'Fields: result'
    type: object
    properties:
      result:
        type: boolean
  adfy.io.rpc.user_SignInRequest:
    description: 'Fields: email, password, rememberMe'
    type: object
    properties:
      email:
        type: string
      password:
        type: string
      rememberMe:
        type: boolean
  adfy.io.rpc.user_SignInResponse:
    description: 'Fields: token'
    type: object
    properties:
      token:
        type: string
