// Code generated by dingo; DO NOT EDIT
package kernel

import (
	projectservice "adfy.io/internal/projectservice"
	userservice "adfy.io/internal/userservice"
	config "adfy.io/pkg/config"
	db "adfy.io/pkg/db"
	jwt "adfy.io/pkg/jwt"
	secure "adfy.io/pkg/secure"
)

type Container struct {
	Config			*config.Config
	Db			*db.Db
	JWT			*jwt.JWT
	Orm			*db.Orm
	ProjectRepository	*projectservice.ProjectRepository
	ProjectService		*projectservice.ProjectService
	Secure			*secure.Secure
	UserRepository		*userservice.UserRepository
	UserService		*userservice.UserService
}

var DefaultContainer = NewContainer()

func NewContainer() *Container {
	return &Container{}
}
func (container *Container) GetConfig() *config.Config {
	if container.Config == nil {
		service := config.NewConfig()
		container.Config = service
	}
	return container.Config
}
func (container *Container) GetDb() *db.Db {
	if container.Db == nil {
		service := db.NewDb(container.GetConfig())
		container.Db = service
	}
	return container.Db
}
func (container *Container) GetJWT() *jwt.JWT {
	if container.JWT == nil {
		service := jwt.NewJWT(container.GetConfig())
		container.JWT = service
	}
	return container.JWT
}
func (container *Container) GetOrm() *db.Orm {
	if container.Orm == nil {
		service := db.NewGorm(container.GetDb())
		container.Orm = service
	}
	return container.Orm
}
func (container *Container) GetProjectRepository() *projectservice.ProjectRepository {
	if container.ProjectRepository == nil {
		service := projectservice.NewProjectRepository(container.GetOrm())
		container.ProjectRepository = service
	}
	return container.ProjectRepository
}
func (container *Container) GetProjectService() *projectservice.ProjectService {
	if container.ProjectService == nil {
		service := projectservice.NewProjectService()
		container.ProjectService = service
	}
	return container.ProjectService
}
func (container *Container) GetSecure() *secure.Secure {
	if container.Secure == nil {
		service := secure.NewSecure(6)
		container.Secure = service
	}
	return container.Secure
}
func (container *Container) GetUserRepository() *userservice.UserRepository {
	if container.UserRepository == nil {
		service := userservice.NewUserRepository(container.GetOrm())
		container.UserRepository = service
	}
	return container.UserRepository
}
func (container *Container) GetUserService() *userservice.UserService {
	if container.UserService == nil {
		service := userservice.NewUserService(container.GetJWT(), container.GetSecure(), container.GetUserRepository())
		container.UserService = service
	}
	return container.UserService
}
