// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: project/service.proto

package project

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ProjectRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ProjectRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ProjectRequestMultiError,
// or nil if none found.
func (m *ProjectRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Website

	if len(errors) > 0 {
		return ProjectRequestMultiError(errors)
	}

	return nil
}

// ProjectRequestMultiError is an error wrapping multiple validation errors
// returned by ProjectRequest.ValidateAll() if the designated constraints
// aren't met.
type ProjectRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectRequestMultiError) AllErrors() []error { return m }

// ProjectRequestValidationError is the validation error returned by
// ProjectRequest.Validate if the designated constraints aren't met.
type ProjectRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectRequestValidationError) ErrorName() string { return "ProjectRequestValidationError" }

// Error satisfies the builtin error interface
func (e ProjectRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectRequestValidationError{}

// Validate checks the field values on ProjectResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ProjectResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectResponseMultiError, or nil if none found.
func (m *ProjectResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Result

	if len(errors) > 0 {
		return ProjectResponseMultiError(errors)
	}

	return nil
}

// ProjectResponseMultiError is an error wrapping multiple validation errors
// returned by ProjectResponse.ValidateAll() if the designated constraints
// aren't met.
type ProjectResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectResponseMultiError) AllErrors() []error { return m }

// ProjectResponseValidationError is the validation error returned by
// ProjectResponse.Validate if the designated constraints aren't met.
type ProjectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectResponseValidationError) ErrorName() string { return "ProjectResponseValidationError" }

// Error satisfies the builtin error interface
func (e ProjectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectResponseValidationError{}
