// @generated by protobuf-ts 2.4.0 with parameter force_server_none,optimize_code_size,enable_angular_annotations,generate_dependencies,// @generated from protobuf file "area/service.proto" (package "adfy.io.rpc.area", syntax proto3),// tslint:disable
import { Inject } from "@angular/core";
import { RPC_TRANSPORT } from "@protobuf-ts/runtime-angular";
import { Injectable } from "@angular/core";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AreaService } from "./service";
import type { Empty } from "../google/protobuf/empty";
import type { EditResponse } from "./service";
import type { EditRequest } from "./service";
import type { GetByProjectResponse } from "./service";
import type { GetByProjectRequest } from "./service";
import type { GetResponse } from "./service";
import type { IdRequest } from "./service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateResponse } from "./service";
import type { CreateRequest } from "./service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service adfy.io.rpc.area.AreaService
 */
export interface IAreaServiceClient {
    /**
     * @generated from protobuf rpc: Create(adfy.io.rpc.area.CreateRequest) returns (adfy.io.rpc.area.CreateResponse);
     */
    create(input: CreateRequest, options?: RpcOptions): UnaryCall<CreateRequest, CreateResponse>;
    /**
     * @generated from protobuf rpc: Get(adfy.io.rpc.area.IdRequest) returns (adfy.io.rpc.area.GetResponse);
     */
    get(input: IdRequest, options?: RpcOptions): UnaryCall<IdRequest, GetResponse>;
    /**
     * @generated from protobuf rpc: GetByProject(adfy.io.rpc.area.GetByProjectRequest) returns (adfy.io.rpc.area.GetByProjectResponse);
     */
    getByProject(input: GetByProjectRequest, options?: RpcOptions): UnaryCall<GetByProjectRequest, GetByProjectResponse>;
    /**
     * @generated from protobuf rpc: Edit(adfy.io.rpc.area.EditRequest) returns (adfy.io.rpc.area.EditResponse);
     */
    edit(input: EditRequest, options?: RpcOptions): UnaryCall<EditRequest, EditResponse>;
    /**
     * @generated from protobuf rpc: Delete(adfy.io.rpc.area.IdRequest) returns (google.protobuf.Empty);
     */
    delete(input: IdRequest, options?: RpcOptions): UnaryCall<IdRequest, Empty>;
}
/**
 * @generated from protobuf service adfy.io.rpc.area.AreaService
 */
@Injectable()
export class AreaServiceClient implements IAreaServiceClient, ServiceInfo {
    typeName = AreaService.typeName;
    methods = AreaService.methods;
    options = AreaService.options;
    constructor(
    @Inject(RPC_TRANSPORT)
    private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Create(adfy.io.rpc.area.CreateRequest) returns (adfy.io.rpc.area.CreateResponse);
     */
    create(input: CreateRequest, options?: RpcOptions): UnaryCall<CreateRequest, CreateResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateRequest, CreateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Get(adfy.io.rpc.area.IdRequest) returns (adfy.io.rpc.area.GetResponse);
     */
    get(input: IdRequest, options?: RpcOptions): UnaryCall<IdRequest, GetResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<IdRequest, GetResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetByProject(adfy.io.rpc.area.GetByProjectRequest) returns (adfy.io.rpc.area.GetByProjectResponse);
     */
    getByProject(input: GetByProjectRequest, options?: RpcOptions): UnaryCall<GetByProjectRequest, GetByProjectResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetByProjectRequest, GetByProjectResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Edit(adfy.io.rpc.area.EditRequest) returns (adfy.io.rpc.area.EditResponse);
     */
    edit(input: EditRequest, options?: RpcOptions): UnaryCall<EditRequest, EditResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<EditRequest, EditResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Delete(adfy.io.rpc.area.IdRequest) returns (google.protobuf.Empty);
     */
    delete(input: IdRequest, options?: RpcOptions): UnaryCall<IdRequest, Empty> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<IdRequest, Empty>("unary", this._transport, method, opt, input);
    }
}
