// @generated by protobuf-ts 2.4.0 with parameter force_server_none,optimize_code_size,enable_angular_annotations,// @generated from protobuf file "project/service.proto" (package "adfy.io.rpc.project", syntax proto3),// tslint:disable
import { Inject } from "@angular/core";
import { RPC_TRANSPORT } from "@protobuf-ts/runtime-angular";
import { Injectable } from "@angular/core";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ProjectService } from "./service";
import type { EditResponse } from "./service";
import type { EditRequest } from "./service";
import type { AllProjectResponse } from "./service";
import type { Empty } from "../google/protobuf/empty";
import type { GetProjectResponse } from "./service";
import type { IdRequest } from "./service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateResponse } from "./service";
import type { CreateRequest } from "./service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service adfy.io.rpc.project.ProjectService
 */
export interface IProjectServiceClient {
    /**
     * @generated from protobuf rpc: CreateProject(adfy.io.rpc.project.CreateRequest) returns (adfy.io.rpc.project.CreateResponse);
     */
    createProject(input: CreateRequest, options?: RpcOptions): UnaryCall<CreateRequest, CreateResponse>;
    /**
     * @generated from protobuf rpc: GetProject(adfy.io.rpc.project.IdRequest) returns (adfy.io.rpc.project.GetProjectResponse);
     */
    getProject(input: IdRequest, options?: RpcOptions): UnaryCall<IdRequest, GetProjectResponse>;
    /**
     * @generated from protobuf rpc: AllProject(google.protobuf.Empty) returns (adfy.io.rpc.project.AllProjectResponse);
     */
    allProject(input: Empty, options?: RpcOptions): UnaryCall<Empty, AllProjectResponse>;
    /**
     * @generated from protobuf rpc: EditProject(adfy.io.rpc.project.EditRequest) returns (adfy.io.rpc.project.EditResponse);
     */
    editProject(input: EditRequest, options?: RpcOptions): UnaryCall<EditRequest, EditResponse>;
    /**
     * @generated from protobuf rpc: DeleteProject(adfy.io.rpc.project.IdRequest) returns (google.protobuf.Empty);
     */
    deleteProject(input: IdRequest, options?: RpcOptions): UnaryCall<IdRequest, Empty>;
}
/**
 * @generated from protobuf service adfy.io.rpc.project.ProjectService
 */
@Injectable()
export class ProjectServiceClient implements IProjectServiceClient, ServiceInfo {
    typeName = ProjectService.typeName;
    methods = ProjectService.methods;
    options = ProjectService.options;
    constructor(
    @Inject(RPC_TRANSPORT)
    private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateProject(adfy.io.rpc.project.CreateRequest) returns (adfy.io.rpc.project.CreateResponse);
     */
    createProject(input: CreateRequest, options?: RpcOptions): UnaryCall<CreateRequest, CreateResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateRequest, CreateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetProject(adfy.io.rpc.project.IdRequest) returns (adfy.io.rpc.project.GetProjectResponse);
     */
    getProject(input: IdRequest, options?: RpcOptions): UnaryCall<IdRequest, GetProjectResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<IdRequest, GetProjectResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AllProject(google.protobuf.Empty) returns (adfy.io.rpc.project.AllProjectResponse);
     */
    allProject(input: Empty, options?: RpcOptions): UnaryCall<Empty, AllProjectResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, AllProjectResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: EditProject(adfy.io.rpc.project.EditRequest) returns (adfy.io.rpc.project.EditResponse);
     */
    editProject(input: EditRequest, options?: RpcOptions): UnaryCall<EditRequest, EditResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<EditRequest, EditResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteProject(adfy.io.rpc.project.IdRequest) returns (google.protobuf.Empty);
     */
    deleteProject(input: IdRequest, options?: RpcOptions): UnaryCall<IdRequest, Empty> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<IdRequest, Empty>("unary", this._transport, method, opt, input);
    }
}
