// @generated by protobuf-ts 2.4.0 with parameter force_server_none,optimize_code_size,enable_angular_annotations,// @generated from protobuf file "project/service.proto" (package "adfy.io.rpc.project", syntax proto3),// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message adfy.io.rpc.project.CreateRequest
 */
export interface CreateRequest {
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string; // required
    /**
     * @generated from protobuf field: string website = 3;
     */
    website: string; // required
}
/**
 * @generated from protobuf message adfy.io.rpc.project.EditRequest
 */
export interface EditRequest {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string website = 3;
     */
    website: string;
}
/**
 * @generated from protobuf message adfy.io.rpc.project.ProjectResponse
 */
export interface ProjectResponse {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string; // required
    /**
     * @generated from protobuf field: bool result = 2;
     */
    result: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateRequest$Type extends MessageType<CreateRequest> {
    constructor() {
        super("adfy.io.rpc.project.CreateRequest", [
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "validate.rules": { string: { minLen: "3", maxLen: "50" } } } },
            { no: 3, name: "website", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "validate.rules": { string: { minLen: "3", maxLen: "50" } } } }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message adfy.io.rpc.project.CreateRequest
 */
export const CreateRequest = new CreateRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EditRequest$Type extends MessageType<EditRequest> {
    constructor() {
        super("adfy.io.rpc.project.EditRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "validate.rules": { string: { uuid: true } } } },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "validate.rules": { string: { minLen: "3", maxLen: "50" } } } },
            { no: 3, name: "website", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "validate.rules": { string: { minLen: "3", maxLen: "50" } } } }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message adfy.io.rpc.project.EditRequest
 */
export const EditRequest = new EditRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProjectResponse$Type extends MessageType<ProjectResponse> {
    constructor() {
        super("adfy.io.rpc.project.ProjectResponse", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "result", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message adfy.io.rpc.project.ProjectResponse
 */
export const ProjectResponse = new ProjectResponse$Type();
/**
 * @generated ServiceType for protobuf service adfy.io.rpc.project.ProjectService
 */
export const ProjectService = new ServiceType("adfy.io.rpc.project.ProjectService", [
    { name: "CreateProject", options: {}, I: CreateRequest, O: ProjectResponse },
    { name: "EditProject", options: {}, I: EditRequest, O: ProjectResponse }
]);
